### PR TITLE
Fix/multi target

### LINKED ISSUE #339: Multi target broken after release 0.5.0
Hi!

I was unsuccessfully trying to use /scrape endpoint in the last release of the exporter (0.5.1). 

Since version 0.5.0 it is not possible to send a http request to the endpoint `/scrape?target=foo:1521` where target is set to the DSN of the Oracle instance to scrape metrics from.

Looking at the code I saw that changes made on #308 removed that feature (done in #234) even though the README says the feature is still there.

Is there any chance that this feature will be included again?

### PR DESCRIPTION
**Pull request by d3vb0ox**
# Description

Added back the support for multi-target /scrape endpoint

Fixes #339

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by lucian-vanghele** [comment]
can anyone fix this? multi target can be a very useful feature...
thanks

**Comment by d3vb0ox** [comment]
> can anyone fix this? multi target can be a very useful feature... thanks

Multi target should work on the fork, please try once, we are still testing few things before raising PR to back to main repo

**Comment by lucian-vanghele** [comment]
I tested it, it seems to work.

**Comment by cjosh-vt** [comment]
does DSN need to be in the same format as the environment variable? ie. `/scrape?target=oracle://user:password@myhost:1521/service`

I'm not having luck running mulit target with this currently, it only shows metrics from the primary target

**Comment by lucian-vanghele** [comment]
> I tested it, it seems to work.

I need to take it back ... 
- I run the exporter without setting any DSN variable. accessing to /metrics shows as expected oracledb_up = 0
- I access http://localhost:9161/scrape?target=oracle://otel@localhost:1521/ORCLPDB1?WALLET=wal and that shows some metrics
- I access again /metrics , suddenly this also shows same metrics
- I access a dummy /scrape?target=something and this one shows same metrics

so it seems metrics are somehow hijacked by the first instance that works

**Comment by d3vb0ox** [comment]
@lucian-vanghele maybe it is happening because the metrics does not have a database identifier 

Testing changes here: #2 

Maybe that should solve the issue

**Comment by lucian-vanghele** [comment]
I tried it .. seems to work now. However, wouldn't be better to just revert the original code (which by mistake was removed in release 0.5.0)? or the changes were too big? (I must say I didn't check)

**Comment by Jansy-rm** [comment]
Works for me too, although only when using usernames/passwords without special characters.

If I use a container/common user 'C##TESTUSER' and use the same URL encoding as I would for the DATA_SOURCE_NAME C%23%23TESTUSER it doesn't work, same issue if there are special characters in the password.

**Comment by lucian-vanghele** [comment]
I didn't try anything special. instead of password I used wallet ..

**Comment by dragon-jet** [comment]
> I didn't try anything special. instead of password I used wallet ..

can u tell me how dose it work? i run in release 0.6.0 with DSN, the Multi target should work just on the fork not in iamseth ,right?

**Comment by Jansy-rm** [comment]
Although I got it to work, I found that too many multi target requests from prometheus crashed the exporter service.

For the databases which I can't install a dedicated exporter on I instead fetch the metrics over a database link and store in a database which has an exporter. I've modified the default exporter SQL so each database is identifiable.

**Comment by dragon-jet** [comment]
> Although I got it to work, I found that too many multi target requests from prometheus crashed the exporter service.
> 
> For the databases which I can't install a dedicated exporter on I instead fetch the metrics over a database link and store in a database which has an exporter. I've modified the default exporter SQL so each database is identifiable.

how to go each database is identifiable can u share for me ？

**Comment by lucian-vanghele** [comment]
another feature which is no longer working in the iamseth repo is [this one](https://github.com/iamseth/oracledb_exporter?tab=readme-ov-file#using-a-multiple-host-data-source-name) which is useful in a dataguard setup.  see [334](https://github.com/iamseth/oracledb_exporter/issues/334)

**Comment by Jansy-rm** [comment]
I've written some plsql which runs a slightly modified version of the
default metric sql over each database link owned by my prometheus schema.
The sql joins db_unique_name from v$database to identify each database.

Ive created a table and materialized  view to hold each metric result. The
plsql truncates the table, loops through each database link inserting the
result into the table and then refreshes the materialized view. The
exporter then queries each MV (I've edited the default metric file)

**Comment by dragon-jet** [comment]
> another feature which is no longer working in the iamseth repo is [this one](https://github.com/iamseth/oracledb_exporter?tab=readme-ov-file#using-a-multiple-host-data-source-name) which is useful in a dataguard setup. see [334](https://github.com/iamseth/oracledb_exporter/issues/334)

Is this feature including the ASM not available so far  in the iamseth repo?

**Comment by dragon-jet** [comment]
> I tried it .. seems to work now. However, wouldn't be better to just revert the original code (which by mistake was removed in release 0.5.0)? or the changes were too big? (I must say I didn't check)

how did u make it work with any cmd or config？

**Comment by lucian-vanghele** [comment]
> > I tried it .. seems to work now. However, wouldn't be better to just revert the original code (which by mistake was removed in release 0.5.0)? or the changes were too big? (I must say I didn't check)
> 
> how did u make it work with any cmd or config？

it is about this fork and the issues I was mentioning [here](https://github.com/truemark/oracledb_exporter/pull/1#issuecomment-2139879481)

**Comment by dragon-jet** [comment]
> > > I tried it .. seems to work now. However, wouldn't be better to just revert the original code (which by mistake was removed in release 0.5.0)? or the changes were too big? (I must say I didn't check)
> > 
> > 
> > how did u make it work with any cmd or config？
> 
> it is about this fork and the issues I was mentioning [here](https://github.com/truemark/oracledb_exporter/pull/1#issuecomment-2139879481)

how dose the issue have been resolved ？however, i access by /metrics or /scrape but also shows same metrics... is that any wrong with it ?  
i use one container docker run --env-file,  specific the DSN is about that:
DATA_SOURCE_NAME=oracle://user:pwd@ip:1521/sid
DATA_SOURCE_NAME=oracle://user:pwd@ip:1521/sid
......
my  prom_jobs config  is about that:
 
- job_name: oracledb-exporter
 metrics_path: /scrape
 static_configs:
    - targets: ["db1"]
       labels:
      db1: orcale:://USER:PWS@IP:1521/SID

    - targets: ["db2"]
       labels:
        db2: oracle:://USER:PWS@IP:1521/SID
        relabel_configs:
       - source_labels: [__address__]
        target_label: __param_target
       - target_label: __address__
        replacement: IP:9162

**Comment by dragon-jet** [comment]
> > > > I tried it .. seems to work now. However, wouldn't be better to just revert the original code (which by mistake was removed in release 0.5.0)? or the changes were too big? (I must say I didn't check)
> > > 
> > > 
> > > how did u make it work with any cmd or config？
> > 
> > 
> > it is about this fork and the issues I was mentioning [here](https://github.com/truemark/oracledb_exporter/pull/1#issuecomment-2139879481)
> 
> how dose the issue have been resolved ？however, i access by /metrics or /scrape but also shows same metrics... is that any wrong with it ? i use one container docker run --env-file, specific the DSN is about that: DATA_SOURCE_NAME=oracle://user:pwd@ip:1521/sid DATA_SOURCE_NAME=oracle://user:pwd@ip:1521/sid ...... my prom_jobs config is about that:
> 
> * job_name: oracledb-exporter
>   metrics_path: /scrape
>   static_configs:
>   
>   * targets: ["db1"]
>     labels:
>     db1: orcale:://USER:PWS@IP:1521/SID
>   * targets: ["db2"]
>     labels:
>     db2: oracle:://USER:PWS@IP:1521/SID
>     relabel_configs:
>     
>     * source_labels: [**address**]
>       target_label: __param_target
>     * target_label: **address**
>       replacement: IP:9162

Finally，it works now！but some sql was incorrect in the default metrics....

**Pull request merged**
